# Generated by Django 2.2.1 on 2019-05-15 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Log',
        ),
    ]
