# Generated by Django 2.2.1 on 2019-05-21 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_auto_20190515_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='auto_search',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', max_length=10),
        ),
    ]
