# Generated by Django 2.2.1 on 2019-05-21 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_log_auto_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('product_name', models.CharField(max_length=255)),
                ('product_price', models.CharField(max_length=255)),
                ('product_advertise', models.CharField(max_length=255)),
                ('product_categories', models.CharField(max_length=255)),
                ('product_categorys', models.CharField(max_length=255)),
                ('rank', models.CharField(max_length=255)),
                ('rank_number', models.IntegerField()),
                ('log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='log.Log')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
