# Generated by Django 2.2.1 on 2019-05-22 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0007_productcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='ProductCode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.ProductCode'),
        ),
    ]
