# Generated by Django 2.2.1 on 2019-05-22 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_items_productcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='ProductCode',
            new_name='product_code',
        ),
    ]
